# Security
api.security.token.secret-key=${JWT_SECRET_KEY}
api.token.jwt.issuer=${JWT_ISSUER}
api.security.token.expiration-hours=3
api.security.refresh-token.expiration-hours=720

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false

# Business Rule
api.max-accounts-per-user=7

# Email
api.email.from=${API_EMAIL_FROM}
api.confirm.email.route=${API_CONFIRM_EMAIL_ROUTE}
api.reject.email.route=${API_REJECT_EMAIL_ROUTE}
api.frontend.url=${API_FRONTEND_URL}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.stmp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
